### ISSUE TITLE
Undefined method gcc-4.9_build_version for OS::Mac::Module

### ISSUE THREAD

**Issue by yesimon** [Homebrew/linuxbrew#404]
It works when I checkout b8dc83d, so I'm suspecting a bad merge.

```
Error: undefined method `gcc-4.9_build_version' for OS::Mac:Module
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/compilers.rb:119:in `block in find_compiler'
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/compilers.rb:106:in `each'
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/compilers.rb:106:in `find_compiler'
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/compilers.rb:99:in `compiler'
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/compilers.rb:82:in `select_for'
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/extend/ENV/shared.rb:123:in `compiler'
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/extend/ENV/std.rb:74:in `setup_build_environment'
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/build.rb:90:in `install'
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/build.rb:179:in `<main>'
```

**Comment by sjackman** [comment]
Yep, looks like it. What was the exact command that you were attempting to run? Also report the output of `brew config`

**Comment by yesimon** [comment]
It was for any `brew install *` command. Also not running linux standalone but have gcc-4.9.2 installed through linuxbrew.

brew config:
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: git@github.com:Homebrew/linuxbrew.git
HEAD: f765cd358e3608cdd3088b71b16868489b73f94e
Last commit: 2 days ago
HOMEBREW_PREFIX: /idi/sabeti-scratch/yesimon/linuxbrew
HOMEBREW_CELLAR: /idi/sabeti-scratch/yesimon/linuxbrew/Cellar
CPU: 16-core 64-bit 6
OS X: 0-x86_64
Xcode: N/A
CLT: N/A
Clang: N/A
X11: N/A
System Ruby: 2.2.1 => /idi/sabeti-scratch/yesimon/linuxbrew/Cellar/ruby/2.2.1/bin/ruby
Perl: /idi/sabeti-scratch/yesimon/local/perl5/perls/perl-5.21.10/bin/perl => /idi/sabeti-scratch/yesimon/local/perl5/perls/perl-5.21.10/bin/perl5.21.10
Python: /idi/sabeti-scratch/yesimon/linuxbrew/bin/python => /idi/sabeti-scratch/yesimon/linuxbrew/Cellar/python/2.7.9/bin/python2.7
Ruby: /idi/sabeti-scratch/yesimon/linuxbrew/bin/ruby => /idi/sabeti-scratch/yesimon/linuxbrew/Cellar/ruby/2.2.1/bin/ruby
Java: 1.8.0
```

**Comment by sjackman** [comment]
I'm not able to replicate this issue, which makes it difficult to troubleshoot. Can you please report the output of `brew install hello --cc=gcc-4.9`?

**Comment by yesimon** [comment]
Strange, that works fine, but without `--cc=gcc-4.9` it fails, even though I have `HOMEBREW_CC=gcc-4.9`.

**Comment by sjackman** [comment]
That is particularly weird.

**Comment by acityinohio** [comment]
I'm also getting this bug when I try to brew upgrade. Here's the error:
```
==> Upgrading 3 outdated packages, with result:
gawk 4.1.2, tmux 2.0, sqlite 3.8.10.1
==> Upgrading gawk
Error: undefined method `gcc-4.9_build_version' for OS::Mac:Module
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/usr/local/linuxbrew/Library/Homebrew/compilers.rb:119:in `block in find_compiler'
/usr/local/linuxbrew/Library/Homebrew/compilers.rb:106:in `each'
/usr/local/linuxbrew/Library/Homebrew/compilers.rb:106:in `find_compiler'
/usr/local/linuxbrew/Library/Homebrew/compilers.rb:99:in `compiler'
/usr/local/linuxbrew/Library/Homebrew/compilers.rb:82:in `select_for'
/usr/local/linuxbrew/Library/Homebrew/extend/ENV/shared.rb:123:in `compiler'
/usr/local/linuxbrew/Library/Homebrew/extend/ENV/std.rb:74:in `setup_build_environment'
/usr/local/linuxbrew/Library/Homebrew/build.rb:90:in `install'
/usr/local/linuxbrew/Library/Homebrew/build.rb:179:in `<main>'
```

Followed by my brew config:

```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/linuxbrew.git
HEAD: f765cd358e3608cdd3088b71b16868489b73f94e
Last commit: 3 days ago
HOMEBREW_PREFIX: /usr/local/linuxbrew
HOMEBREW_CELLAR: /usr/local/linuxbrew/Cellar
CPU: quad-core 64-bit 6
OS X: 0-x86_64
Xcode: N/A
CLT: N/A
Clang: N/A
X11: N/A
System Ruby: 2.2.2 => /usr/local/linuxbrew/Cellar/ruby/2.2.2/bin/ruby
Perl: /usr/local/linuxbrew/bin/perl => /usr/local/linuxbrew/Cellar/perl/5.20.1/bin/perl
Python: /usr/local/linuxbrew/bin/python => /usr/local/linuxbrew/Cellar/python/2.7.9/bin/python2.7
Ruby: /usr/local/linuxbrew/bin/ruby => /usr/local/linuxbrew/Cellar/ruby/2.2.2/bin/ruby
Java: N/A
```

**Comment by acityinohio** [comment]
And likewise, installing `brew hello` fails unless I use the `--cc=gcc4.9` flag, even though I have `HOMEBREW_CC=gcc-4.9`. Really weird!

**Comment by sjackman** [comment]
Does `brew upgrade --cc=gcc4.9` work?
It looks as though the handling of `HOMEBREW_CC` has changed in some odd way.

**Comment by acityinohio** [comment]
Yup! That did the trick.

**Comment by iggyvolz** [comment]
Appropriate lines of code:
https://github.com/Homebrew/homebrew/blob/6dd602f073a97094839d05d2126d944434b5c752/Library/ENV/4.3/cc#L43 (unchanged in linuxbrew)

```ruby
  def tool
    @tool ||= case @arg0
    when 'ld' then 'ld'
    when 'cpp' then 'cpp'
    when /\w\+\+(-\d\.\d)?$/
      case ENV['HOMEBREW_CC']
      when /clang/
        'clang++'
      when /llvm-gcc/
        'llvm-g++-4.2'
      when /gcc(-\d\.\d)?$/
        'g++' + $1.to_s
      end
    else
      # Note that this is a universal fallback, so that we'll always invoke
      # HOMEBREW_CC regardless of what name under which the tool was invoked.
      ENV['HOMEBREW_CC']
    end
  end
```

I'm not a ruby expert, but it looks like homebrew hijacks the gcc-* and changes it to g++-*, likely for Mac compatibility purposes.  I wonder if taking this section completely out and just changing it to ENV['HOMEBREW_CC'] would solve the problem without breaking anything else.

**Comment by sjackman** [comment]
That code is specific to `--env=super`, which Linuxbrew does not use nor support. See https://github.com/Homebrew/linuxbrew/pull/266 which adds superenv support to Linuxbrew. The default on Linuxbrew is `--env=std`.

**Comment by yesimon** [comment]
Spent some time on this: looks like this isn't just a linuxbrew problem:

On Mac:
```
simon@nitrogen ~> env HOMEBREW_CC=gcc-4.9 brew install hello --env=std --build-from-source
gcc-4.9
Error: undefined method `gcc-4.9_build_version' for OS::Mac:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/compilers.rb:116:in `block in find_compiler'
/usr/local/Library/Homebrew/compilers.rb:106:in `each'
/usr/local/Library/Homebrew/compilers.rb:106:in `find_compiler'
/usr/local/Library/Homebrew/compilers.rb:99:in `compiler'
/usr/local/Library/Homebrew/compilers.rb:82:in `select_for'
/usr/local/Library/Homebrew/extend/ENV/shared.rb:119:in `compiler'
/usr/local/Library/Homebrew/extend/ENV/std.rb:56:in `setup_build_environment'
/usr/local/Library/Homebrew/build.rb:90:in `install'
/usr/local/Library/Homebrew/build.rb:179:in `<main>'
```

The cause is Homebrew/homebrew@9c74f42962090c016143744b057e13aa75d9b13e. There have always been different code paths for `--cc=gcc-1.9` and `env HOMEBREW_CC=gcc-4.9`, and only the env var calls into `find_compiler` which has changed logic. @jacknagel any thoughts on that commit?

**Comment by yesimon** [comment]
Also `brew config` on mac.

```

**Comment by jacknagel** [comment]
Fixed upstream in Homebrew/homebrew@43c634ffc2ee0514260cdf6f050a6e8be4035240

**Comment by sjackman** [comment]
Merged today. Thanks, Jack.
