### ISSUE TITLE
python3 formula not working on CentOS 6.4

### ISSUE THREAD

**Issue by hammer** [Homebrew/linuxbrew#83]
`make` dies with

```
./Modules/getpath.c:575: warning: implicit declaration of function ‘NSModuleForSymbol’
./Modules/getpath.c:575: warning: implicit declaration of function ‘NSLookupAndBindSymbol’
./Modules/getpath.c:577: warning: implicit declaration of function ‘NSLibraryNameForModule’
make: *** [Modules/getpath.o] Error 1
```
