### ISSUE TITLE
gcc 5 fails to build on Ubuntu 14.10

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/linuxbrew#479]
_From @toebbel on July 13, 2015 15:35_

Fresh linux brew installation. Brew doctor has no complains.
https://gist.github.com/toebbel/5b51db15df0ca6151639

_Copied from original issue: Homebrew/homebrew#41664_

**Comment by sjackman** [comment]
Please report `brew gist-logs gcc`

**Comment by toebbel** [comment]
I see "Error: No logs". Tried to re-run the install but still "no logs".

**Comment by sjackman** [comment]
Please report the exact output of
```sh
brew install gcc
```

**Comment by sjackman** [comment]
```
/usr/bin/g++-4.9 -Os -w -pipe -march=core2  -Isrc/abstraction -Isrc/ld -isystem/home/tobi/.linuxbrew/include  -c -o src/other/ObjectDump.o src/other/ObjectDump.cpp
In file included from /home/tobi/.linuxbrew/include/mach-o/loader.h:35:0,
                 from src/abstraction/MachOFileAbstraction.hpp:27,
                 from src/ld/MachOReaderRelocatable.hpp:37,
                 from src/other/ObjectDump.cpp:31:
/home/tobi/.linuxbrew/include/mach/machine.h:66:35: fatal error: mach/machine/vm_types.h: No such file or directory
 #include <mach/machine/vm_types.h>
```
https://gist.github.com/toebbel/5b51db15df0ca6151639#file-gistfile1-txt-L11-L17

**Comment by sjackman** [comment]
Ah, I bet you're trying to `brew install gcc5`. That won't work. `homebrew/versions` isn't entirely supported on Linuxbrew.

**Comment by sjackman** [comment]
You'll want to remove whatever packages were installed when you tried `brew install gcc5`.
`brew remove cctools-headers dyld-headers libunwind-headers`
