### ISSUE TITLE
git: [Ubuntu 14.04] Git fails to build with system curl and gcc 4.8

### ISSUE THREAD

**Issue by davydden** [Homebrew/linuxbrew#713]
subj.

```
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `SSL_CTX_load_verify_locations@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `i2t_ASN1_OBJECT@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `ERR_remove_thread_state@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `RAND_bytes@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `MD5_Update@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `UI_method_get_writer@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `SSL_CIPHER_get_name@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `X509_EXTENSION_get_critical@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `PKCS12_free@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `sk_num@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `ERR_error_string@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `X509_NAME_print_ex@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `UI_method_set_writer@OPENSSL_1.0.0'
```

a workaround is to
```
brew install curl
brew install git --without-tcl-tk --with-brewed-curl
```
but i would still want to know why it fails...

**Comment by sjackman** [comment]
I don't know why it fails, but I recommend using
`brew install git --with-brewed-curl --with-brewed-openssl --without-tcl-tk`
In fact, `--without-tcl-tk` is already the default, and I plan on changing `--with-brewed-curl --with-brewed-openssl` to the default as well. See also #700

**Comment by sjackman** [comment]
The options `--with-brewed-curl --with-brewed-openssl --without-tcl-tk` are now all default.
Does it build now with the system GCC 4.8?
