### ISSUE TITLE
I can't install mongodb

### ISSUE THREAD

**Issue by hemedani** [Homebrew/linuxbrew#378]
I want to install mongodb with brew in ubuntu 15.04 but despite several attempts to install i can't do that, even if I completely remove homebrew and reinstall it. when i type in terminal :
`   brew install mongodb`

says :
`==> Installing dependencies for mongodb: go, scons`

and completely fine for installing dependencies :
```bash
==> Installing mongodb dependency: go
==> Downloading https://storage.googleapis.com/golang/go1.4.2.src.tar.gz
######################################################################## 100.0%
==> Building go for -linux
==> ./make.bash --no-clean
==> Cloning https://go.googlesource.com/tools.git
Cloning into '/home/amir/.cache/Homebrew/go--gotools--git'...
remote: Total 13119 (delta 9226), reused 13119 (delta 9226)
Receiving objects: 100% (13119/13119), 5.96 MiB | 22.00 KiB/s, done.
Resolving deltas: 100% (9226/9226), done.
Checking connectivity... done.
==> Checking out revision 69db398fe0e69396984e3967724820c1f631e971
==> go build
==> go build
==> Caveats
As of go 1.2, a valid GOPATH is required to use the `go get` command:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/home/amir/.linuxbrew/opt/go/libexec/bin

==> Summary
/home/amir/.linuxbrew/Cellar/go/1.4.2: 4566 files, 161M, built in 12.7 minutes
==> Installing mongodb dependency: scons
==> Downloading https://downloads.sourceforge.net/scons/scons-2.3.4.tar.gz
######################################################################## 100.0%
==> /usr/bin/python setup.py install --prefix=/home/amir/.linuxbrew/Cellar/scons/2.3.4 --standalone-lib --install-lib=/home
/home/amir/.linuxbrew/Cellar/scons/2.3.4: 405 files, 4.5M, built in 31 seconds
```

but when it was to install mongo says:
```bash
==> Installing mongodb
==> Downloading https://fastdl.mongodb.org/src/mongodb-src-r3.0.2.tar.gz
######################################################################## 100.0%
==> Cloning https://github.com/mongodb/mongo-tools.git
Cloning into '/home/amir/.cache/Homebrew/mongodb--github.com-mongodb-mongo-tools--git'...
remote: Counting objects: 1138, done.
remote: Compressing objects: 100% (908/908), done.
remote: Total 1138 (delta 187), reused 780 (delta 143), pack-reused 0
Receiving objects: 100% (1138/1138), 1.79 MiB | 26.00 KiB/s, done.
Resolving deltas: 100% (187/187), done.
Checking connectivity... done.
Note: checking out 'bc08e57abb71b2edd1cc3ab8f9f013409718f197'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

==> Checking out tag r3.0.1
==> ./build.sh
==> /home/amir/.linuxbrew/opt/scons/bin/scons install --prefix=/home/amir/.linuxbrew/Cellar/mongodb/3.0.2 -j2 --cc=/usr/bin
src/third_party/boost/boost/math/special_functions/fpclassify.hpp:287:6: error: 'J' does not name a type
     }J
      ^
scons: *** [build/linux2/cc__usr_bin_gcc-4.9/cxx__usr_bin_g++-4.9/mongo/bson/bsonobjbuilder.o] Error 1
scons: building terminated because of errors.

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
mongodb fails to build on 10.7 (https://github.com/Homebrew/homebrew/issues/37691)
fix homebrew.mxcl.mongodb.plist open file limits (https://github.com/Homebrew/homebrew/pull/38871)
```

how can i fixed...
tanx

**Comment by sjackman** [comment]
I'm afraid I don't the time to troubleshoot individual formula. Please report back here if you're able to find a workaround or fix. Sorry I couldn't be of more help.

**Comment by iggyvolz** [comment]
I would open an issue at https://github.com/mongodb/mongo-tools specifically.

Running a brew gist-logs and pointing them to it should work fine.  A good title for the issue would be "fpclassify.hpp: 'J' does not name a type in Ubuntu 15.04".  If you need any help feel free to @iggyvolz in the discussion and I can try to help if I get free time.

**Comment by sjackman** [comment]
Thanks for all your help with support, Iggy. I appreciate it.

**Comment by hemedani** [comment]
Tanks iggy...
after all i installed mongo with apt-get
just for everyone who read this issue for installing mongo with apt-get don't adding the vivide repo adding the trusty repo
