### ISSUE TITLE
w3m failed to build on Slackware 14.1 and on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by retokromer** [Homebrew/linuxbrew#708]
`brew gist-logs w3m` output:
https://gist.github.com/28684d820ba446e07e21

Terminal output:

```
[13:19:58]why@why:~/Desktop$ brew install w3m
==> Downloading https://downloads.sourceforge.net/project/w3m/w3m/w3m-0.5.3/w3m-
Already downloaded: /home/why/.cache/Homebrew/w3m-0.5.3.tar.gz
==> Patching
patching file main.c
==> ./configure --prefix=/home/why/.linuxbrew/Cellar/w3m/0.5.3 --disable-image -
==> make install
Last 15 lines from /home/why/.cache/Homebrew/Logs/w3m/02.make:
                 from fm.h:39,
                 from main.c:3:
istream.h:23:8: error: redefinition of ‘struct file_handle’
 struct file_handle {
        ^
In file included from /usr/include/x86_64-linux-gnu/bits/fcntl.h:61:0,
                 from /usr/include/fcntl.h:35,
                 from istream.h:14,
                 from html.h:10,
                 from fm.h:39,
                 from main.c:3:
/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h:311:8: note: originally defined here
 struct file_handle
        ^
make: *** [main.o] Error 1

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

[13:20:15]why@why:~/Desktop$
```

**Comment by sjackman** [comment]
This bug was reported in #159 and fixed in f383493, but was somehow unintentionally reverted, probably in a merge. It's fixed once again. Thanks for the bug report.

**Comment by sjackman** [comment]
I'm seeing the following error. Did you happen to encounter this error?

```
checking GC library exists... yes
checking gc.h usability... yes
checking gc.h presence... yes
checking for gc.h... yes
checking for GC_init in -lgc... no
checking GC library location... /usr /usr/local /var/tmp/sjackman/w3m20160109-28154-s4gmh8/w3m-0.5.3/.brew_home
checking /usr... checking for GC_init in -lgc... no
checking /usr/local... checking for GC_init in -lgc... no
checking /var/tmp/sjackman/w3m20160109-28154-s4gmh8/w3m-0.5.3/.brew_home... checking for GC_init in -lgc... no
configure: error: libgc not found
```

**Comment by retokromer** [comment]
Sorry, I cant't check it on Slackware now, but on Ubuntu I have
`checking for GC_init in -lgc... yes`
followed by
`checking for zError in -lz... yes`

**Comment by retokromer** [comment]
Neither on a Slackware test machine I do experience «your» error. This part runs well on my side. – Yet I do not longer have a «pure» linuxbrew configuration. I’ll try this afternoon to have some inspiration on the issue. (I’m not feeling well those days, therefore no guarantee. I had a stroke five years ago, and since I’m a… little fragile, as in my picture ;-)

**Comment by sjackman** [comment]
No worries, Reto. It was more of a curiosity question. I suspect that the build script needs a flag to tell it where the `gc` library is located.

**Comment by retokromer** [comment]
Neither on Slackware I can reproduce that error.

Also this formula is now working well. Thank you again, @sjackman!

**Comment by sjackman** [comment]
No worries. I'm glad that I could help.
